### PR TITLE
Simplify itermocil formula

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by ruudk** [comment]
@godbout Please have a look, I tested this and it works! 

Maybe good that from now on, we tag each other in our changes, and always create a PR, instead of directly pushing to `master`.

@TomAnthony Can you maybe setup some branch protection for this repo + itermocil repo?? So that direct commits to master are disallowed, and that at least 1 reviewer is needed? Otherwise it's not safe.

**Comment by godbout** [comment]
> @godbout Please have a look, I tested this and it works!

why forcing Python 3.10 minimum?
rest looks good to me but again i'm not safe to judge 😅️

> Maybe good that from now on, we tag each other in our changes, and always create a PR, instead of directly pushing to `master`.

agreed, yeah. even in my own repos, working by myself, i'd always go through PRs. just for the little explanation: because i've stopped using my own fork to work on this one, iTermocil wasn't working while i was trying to work on another project. i tried to do the changes properly but having no knowledge of the Python ecosystem (envs, testing etc) and not wanting to spend time on that now, i went straight to make iTermocil work as fast as possible for now. as you can see there's even several crappy releases because i didn't know/didn't want to find how to test a non-master tap through Homebrew, etc.

all of this to say that ultimately, you could take this repo over. i was just interested in making iTermocil work with Python 3. but i don't have the skills and the time to collaborate on it i think, and more importantly to collaborate properly.

**Comment by TomAnthony** [comment]
> @TomAnthony Can you maybe setup some branch protection for this repo + itermocil repo?? So that direct commits to master are disallowed, and that at least 1 reviewer is needed? Otherwise it's not safe.

Done (I think!). Wasn't necessary when it was just me! Let me know if it isn't working.

**Comment by ruudk** [comment]
> why forcing Python 3.10 minimum?

Why not, it's running in virtualenv now, so let's just use the latest version.

@godbout Could you please approve the PR so that we can merge this? Thanks!

**Review by godbout — APPROVED** [review]

**Comment by godbout** [comment]
> Why not, it's running in virtualenv now, so let's just use the latest version.

😵️ so wait, does that mean there's no need to install Python manually before installing iTermocil? the setup will take care of that? if yes then i'll remove that step from the README.

**Comment by ruudk** [comment]
No, because Brew automatically installs the dependencies :) That's the beauty of a package manager like brew.

**Comment by godbout** [comment]
@ruudk my bad, i didn't express myself correctly. i'm talking about the python environments. Homebrew installs stuff globally. as least afaik. like for PHP, if you have different projects using different versions of PHP, you have to handle the virtual envs through other means (like docker), or manually switch your global PHP when you switch projects. seems that what you're saying here is that the iTermocil install will install Python 3.10 ONLY for iTermocil. i could have other projects using 3.9, or the Xcode 3.8 version. if that's the case i wasn't aware of this being possible. but that's Python ecosystem thing no? anyways, if that's the case, very cool. thanks.

**Comment by ruudk** [comment]
I think this is handled by using virtualenv, which just isolates Python versions per version.

**Comment by godbout** [comment]
yeah, that's what i guessed. seems that's the case: https://formulae.brew.sh/formula/virtualenv
had no idea. again, 0 Python here. that is pretty cool! i'm gonna remove that step from the README then. through PR ;) :p

**Pull request merged**
